name: music_api
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'
  
dependencies:
  flutter:
    sdk: flutter
  youtube_data_api: ^1.0.4
  shared_preferences: ^2.2.2
  youtube_player_iframe: ^4.0.4
  cloud_firestore: ^5.2.1
  firebase_storage: ^12.1.3
  firebase_auth: ^5.1.4
  google_sign_in: ^6.2.1
  provider: ^6.1.1
  super_tooltip: ^2.0.7
  flutter_naver_map: ^1.1.2
  geolocator: ^10.1.0
  image_gallery_saver: ^2.0.3
  image_picker: ^1.0.7
  firebase_core: ^3.3.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/fonts/images/

    
  fonts:
    - family: Pretendard
      fonts:
        - asset: assets/fonts/Pretendard-Black.otf
        - asset: assets/fonts/Pretendard-Bold.otf
        - asset: assets/fonts/Pretendard-ExtraBold.otf
        - asset: assets/fonts/Pretendard-ExtraLight.otf
        - asset: assets/fonts/Pretendard-Light.otf
        - asset: assets/fonts/Pretendard-Medium.otf
        - asset: assets/fonts/Pretendard-Regular.otf
        - asset: assets/fonts/Pretendard-SemiBold.otf
        - asset: assets/fonts/Pretendard-Thin.otf
        - asset: assets/fonts/KimjungchulMyungjo-Regular.otf