// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsciwPXoWNu5eQpQHQCGTQhhuxIVYyDNc',
    appId: '1:859784822505:web:7ab6954a4fc95224f8fa78',
    messagingSenderId: '859784822505',
    projectId: 'music-9b7aa',
    authDomain: 'music-9b7aa.firebaseapp.com',
    storageBucket: 'music-9b7aa.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLd_38Hdi4n3SDrIDQHw1zkeXEbuY4elw',
    appId: '1:859784822505:android:fdf5b20d1b093013f8fa78',
    messagingSenderId: '859784822505',
    projectId: 'music-9b7aa',
    storageBucket: 'music-9b7aa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-Ad0zeWK8jZjs5hCYxzdWfw-uUkaP1dY',
    appId: '1:859784822505:ios:c2a7193344c3b4a2f8fa78',
    messagingSenderId: '859784822505',
    projectId: 'music-9b7aa',
    storageBucket: 'music-9b7aa.appspot.com',
    iosBundleId: 'com.example.musicApi',
  );
}
